# Generated by Django 5.0.1 on 2024-01-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("transaction_ref", models.CharField(max_length=255, unique=True)),
                ("amount", models.IntegerField()),
                ("gateway_ref", models.CharField(max_length=255)),
                ("transaction_status", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255)),
                ("merchant_id", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=3)),
                ("transaction_type", models.CharField(max_length=50)),
                ("merchant_amount", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("payment_information", models.JSONField()),
                ("is_recurring", models.BooleanField()),
                ("meta", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="PaymentLink",
        ),
    ]
